Sample data update (#180)
pnp/vscode-viva pull request #199
Opened 2024-03-19 16:53 UTC by hugoabernier

Automated check and update of SPFx extensions and webparts samples data
and aces sample data.

Co-authored-by: Adam-it <Adam-it@users.noreply.github.com>## 🎯 Aim

Adds support for NVM, NVS, or no Node Version Manager, and a VS Code Setting to control the choice.

## 📷 Result

![image](https://github.com/pnp/vscode-viva/assets/13972467/1e0f7a21-10db-442d-9c6e-7e10fd21cd64)

## ✅ What was done

Added a VSCode setting, and logic to change the command when launching a new terminal.

- [] not done
- [X] done

## 🔗 Related issue

No issues man, we're all good!

2024-03-20 01:26 UTC, Adam-it requested changes
@hugoabernier awesome work 👏
tested locally, works really good ✅
I added a few clean up comments. Please recheck them before we merge 👍
Let me know if something is unclear 🙏

2024-03-20 01:26 UTC, Adam-it commented on src/services/TerminalCommandExecuter.ts
> +        }
in `constants` folder lets create a new enum `NodeVersionManagers` like

```
export enum NodeVersionManagers {
  nvm = 'nvm',
  nvs = 'nvs',
  none = 'none'
}
```

and use it here, also let's use it in line 79 like 
`const nodeVersionManager: string = TerminalCommandExecuter.getExtensionSettings('nodeVersionManager', NodeVersionManagers.none);`

also lets remove the not needed comments
```suggestion
      // If there are .nvmrc files and the user wants to use nvm, then use their preferred node version manager
      if (nvmFiles.length > 0 && nodeVersionManager !== NodeVersionManagers.none) {
        if (nodeVersionManager === NodeVersionManagers.nvs) {
          terminal.sendText('nvs use');
        } else {
          terminal.sendText('nvm use');
        }
      }
```

2024-03-20 01:31 UTC, Adam-it commented
@hugoabernier Thank you for this awesome suggestion and PR. 
I rebased the `dev` branch so that this PR is now clean. Please for future reference start your branch from `dev` not `main`  to avoid unnecessary conflicts👍
I reviewed your PR and added a few minor comments. Mostly small clean up details. Please double-check them and after they are  resolved click on the `ready to review` button on this PR so we may proceed with merging 👍
Also please do let me know if something is unclear or the SPFx workshop you mentioned is coming shortly and you won't have time to resolve those comments, in that case, I will do that for you 😉.
As soon as this is merge I will create a new pre-release so you may start using Viva Toolkit with this change ASAP.
I plan to do next minor/major by the end of this month.
Cheers.

2024-03-22 14:36 UTC, hugoabernier commented
@Adam-it looks great, please proceed at your convenience

2024-03-22 23:55 UTC, Adam-it approved these changes

2024-03-22 23:55 UTC, Adam-it approved these changes

2024-03-22 23:56 UTC, merged

2024-03-22 23:59 UTC, Adam-it commented
Merged manually.
Thank you for your awesome work 👏

2024-03-23 00:22 UTC, Adam-it commented
@hugoabernier your change is present in the latest pre-release 2.6.1 🚀
![image](https://github.com/pnp/vscode-viva/assets/58668583/d7ba10db-35b8-4c23-b6a1-50f606abc0c1)

remember that in order to install a pre-release you need to click on the `switch to pre-release` button in the extension view in VS Code to opt-in.

Thank you for contributing to Viva Toolkit 👏