Refactors scaffolding form to smaller components. Closes #221
pnp/vscode-viva pull request #242
Opened 2024-05-28 08:51 UTC by Saurabh7019

## 🎯 Aim

> This PR refactors scaffolding form to smaller components

## 📷 Result

> ![image](https://github.com/pnp/vscode-viva/assets/18114579/fcbf9fcc-18b9-44c6-9b96-62eaf206a0f2)

## ✅ What was done

- [X] Moved the header section into a separate `FormHeader` component.
- [X] Moved the general information section into a separate `GeneralInfoStep` component.
- [X] Moved the component details section into a separate `ComponentDetailsStep` component.
- [X] Moved the additional steps section into a separate `AdditionalStep` component.
- [X] Moved the form action buttons and the progress indicator into a separate `FormActions` component.
- [X] Maintained the state management within the main component `ScaffoldSpfxProjectView`.
- [X] Added a slight delay to fix terminal receiving `pm i` instead of `npm i` when `npm install` checkbox is selected

## 🔗 Related issue

> Closes: #221

2024-05-29 00:12 UTC, Adam-it commented
@Saurabh7019 thank you for this awesome change 🚀 You rock 🤩
I will review it ASAP

2024-06-03 20:56 UTC, Adam-it requested changes
tested locally ✅
Awesome work so far 👍.
I left a few minor comments. Lets recheck them before we proceed

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
> +interface AdditionalStepProps {
Please leave two empty lines between imports and the rest of the code. 
I should probably add an eslint rule for that 🤔, Sorry my bad 😉

```suggestion
import { PackageSelector } from './PackageSelector';


interface AdditionalStepProps {
```

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/PackageSelector.tsx
> +                {link ? <>Install <VSCodeLink href={link}>{label}</VSCodeLink> {additionalLabel}</> : `Install ${label}`}
maybe let's extract `Install` word so that it should be also part of passes `label`. One of the features we want to add for future is to provide adding custom additional steps and at that point it is the dev that will provide the label. It could be might as well `Add ...` instead of `Install`

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/PackageSelector.tsx
> +    additionalLabel }: React.PropsWithChildren<PackageSelectorProps>) => {
I would get rid of `additionalLabel` prop and for the PnPjs just pass the `(@pnp/sp, @pnp/graph)` as part of the label. Ok It will be before the link but will make this less specific and more reusable for near future and other additional dependencies we want to add

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
> +                    additionalLabel="(@pnp/sp, @pnp/graph)" />
let's remove this one and just apss it as part of `label` prop

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/FormHeader.tsx
> +export interface IFormHeaderProps {
Let's keep two break lines betewwn the imports and the rest of the code

```suggestion


export interface IFormHeaderProps {
```

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/PackageSelector.tsx
> +interface PackageSelectorProps {
```suggestion
import { VSCodeButton, VSCodeLink } from '@vscode/webview-ui-toolkit/react';


interface PackageSelectorProps {
```

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/StepHeader.tsx
> +export interface IStepHeaderProps {
```suggestion
import * as React from 'react';


export interface IStepHeaderProps {
```

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/FormActions.tsx
> +export interface IFormActionsProps {
```suggestion
import { AddIcon } from '../../icons';


export interface IFormActionsProps {
```

2024-06-03 20:56 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/GeneralInfoStep.tsx
> +export interface IGeneralInfoProps {
```suggestion
import { Messenger } from '@estruyf/vscode/dist/client';


export interface IGeneralInfoProps {
```

2024-06-04 09:09 UTC, Saurabh7019 commented
Hi @Adam-it , I just noticed that the extension loads fine on the `main` branch, but it doesn’t seem to load on the `dev` branch. When you have a chance, could you please check if it works for you?

2024-06-04 09:30 UTC, Adam-it commented
> Hi @Adam-it , I just noticed that the extension loads fine on the `main` branch, but it doesn’t seem to load on the `dev` branch. When you have a chance, could you please check if it works for you? 

Sure will check, but that's rather strange as latest pre-release 3.2.1 was created from dev branch. So it would not work after downloading from marketplace as well 🤔.

What seems to be the issue?

2024-06-04 10:37 UTC, Saurabh7019 commented
> What seems to be the issue?

I’m running the watch command on the dev branch and trying to start the extension, but the extension doesn’t show up at all. I don’t see any errors in the debug console that could explain this behavior.

2024-06-04 12:05 UTC, Adam-it commented
> > What seems to be the issue?
> 
> I’m running the watch command on the dev branch and trying to start the extension, but the extension doesn’t show up at all. I don’t see any errors in the debug console that could explain this behavior.

I just checked clean `dev` branch without any changes works ok
![image](https://github.com/pnp/vscode-viva/assets/58668583/9722140e-2126-4f1f-854b-81f4d85e164d)


in the debug VSCofe instance do you see anything in the `extension host` output
![image](https://github.com/pnp/vscode-viva/assets/58668583/b7ed8371-dab6-485d-8bac-3cfc58070969)

2024-06-05 07:24 UTC, Saurabh7019 commented
![image](https://github.com/pnp/vscode-viva/assets/18114579/da70bff5-7ed7-48d8-b8f7-aab56cb0f33b)

I can't seem to figure it out. A fresh clone of the dev branch works fine. I will work with that and make the suggested changes today. I apologize for wasting your time with this.

2024-06-05 08:04 UTC, Saurabh7019 commented on src/extension.ts
> +	const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
I have reverted the change, and I will create a new issue if I can reproduce it in the latest release.

2024-06-05 08:05 UTC, Saurabh7019 commented on src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
> +interface AdditionalStepProps {
Please let me know if you would like me to add the rule.

2024-06-06 13:45 UTC, Adam-it commented
> ![image](https://github.com/pnp/vscode-viva/assets/18114579/da70bff5-7ed7-48d8-b8f7-aab56cb0f33b)
> 
> I can't seem to figure it out. A fresh clone of the dev branch works fine. I will work with that and make the suggested changes today. I apologize for wasting your time with this.
> 

No apologies needed 👍, all good. 
From my experience writing VS Code extensions is sometimes glitchy and couple of times already I had those WT* moments as well 😅.
Glad that it is working now. Cheers 👍

2024-06-10 22:38 UTC, Adam-it approved these changes
tested locally ✅
LGTM 👍

2024-06-10 22:40 UTC, merged