Issue 155
pnp/vscode-viva pull request #259
Opened 2024-06-18 05:27 UTC by DevPio

## 🎯 Aim

This pull request introduces several enhancements to improve the user experience and functionality of the application:

Filter Management Enhancement: Implemented a feature to display selected filters prominently and provide a clear button to reset filters, inspired by TT's intuitive design.

Filter State Persistence: Fixed an issue where navigating back from the detail view would reset filter selections, ensuring that selected filters persist across navigation sessions.

Scroll Behavior Improvement: Addressed a UI issue in the samples gallery where scrolling position in detail views was not consistently reset to the top, now ensuring a consistent user experience.

These enhancements aim to enhance usability, streamline user interaction with filters, and improve overall navigation consistency within the application.

## 📷 Result

![1](https://github.com/pnp/vscode-viva/assets/64063580/43dfea1f-fcf3-440b-8a75-8902546bfbaa)

![2](https://github.com/pnp/vscode-viva/assets/64063580/92e25eb6-e0fd-4a8b-8f2d-b1b671a0cdcf)

![3](https://github.com/pnp/vscode-viva/assets/64063580/d3c5183e-d411-4a64-ac48-b53a15b12909)

## ✅ What was done

- [X] Added selected filters and clear filters button, similar to TT's style, with tags representing each filter set and a button to clear all selected filters.

- [X]  Fixed issue where navigating back from the detail view didn't preserve filter state, now filters remain selected as expected.

- [X]  Addressed issue in samples gallery where scrolling in the previous view not at the top resulted in lower scroll position in detail view; now sets scroll position to the top.

## 🔗 Related issue

Closes: #155

2024-06-18 06:14 UTC, Adam-it commented
Thanks you for this awesome work 👏👏
You Rock 🤩 
I will review it ASAP

2024-06-29 22:15 UTC, Adam-it requested changes
@DevPio awesome work 👏
works nicely ✅
I added a few comments. Some are small related to styling but others are something a bit bigger we could recheck and correct before we proceed with merging. like:
- seems we in some places we lack formatting like adding additional ` ` between elements of an array or brackets etc. Let's be sure to use VS Code formatted to resolve all that 👍
- in tags let's use display name for component types when showing the value. so it should be `Web Part` not `WEBPART` or `ACE` not `ADAPTIVECARDEXTENSION`
![image](https://github.com/pnp/vscode-viva/assets/58668583/d2f150e3-7db0-4e15-ab4b-6136fd4d4b7f)

Please go over my review before we move forward with this 👍 Thanks a lot! You Rock 🤩
Sorry for the hold up and wait from my side 🙏

2024-06-29 22:15 UTC, Adam-it commented on src/webview/view/components/gallery/SearchBar.tsx
> +            return <div className={'p-1 cursor-pointer'} onClick={() => onRemoveFilterBySPFxVersion(filter.key as string)}><VSCodeTag key={index} >{filter.key} <strong>X</strong></VSCodeTag></div>;
instead of using X as text lets use the close icon from codicons 
https://microsoft.github.io/vscode-codicons/dist/codicon.html
to do that you need to find it in the repo https://github.com/microsoft/vscode-codicons/tree/main/src/icons
Copy its svg and add it to the webview/view/components/icons folder and then you may use it as any other icon in this project 👍

2024-06-29 22:15 UTC, Adam-it commented on src/webview/view/components/gallery/SearchBar.tsx
> +        {(selectedFilters.length > 0 || query)&& <div className={'p-1 cursor-pointer'} onClick={clearAllFilters}><strong style={{color:'#3664be'}}>Clear all</strong></div>}
why not use `label` instead of `div`? label initial cursor behavior is already `cursor` so we wont need to fix this as well.
also lets not set any inline custom styling. If we need lets extract it using a custom CSS class and add styles to index.css.
also lets not add static colors but use VS Code variables for colors like `var(--vscode-textLink-foreground)`
if we use static colors we may not guarantee it will look ok for every VS Code theme

![image](https://github.com/pnp/vscode-viva/assets/58668583/be300a2f-4be7-48b5-b325-f5aa9a5764be)

2024-06-30 06:33 UTC, DevPio commented on src/webview/view/components/gallery/SearchBar.tsx
> +export const SearchBar: React.FunctionComponent<ISearchBarProps> = ({ onSearchTextboxChange, onFilterBySPFxVersionChange, onFilterByComponentTypeChange, onFilterOnlyScenariosChange, initialQuery, spf
```suggestion
export const SearchBar: React.FunctionComponent<ISearchBarProps> = ({ onSearchTextboxChange, onFilterBySPFxVersionChange, onFilterByComponentTypeChange, onFilterOnlyScenariosChange, initialQuery, spfxVersions, selectedFilters,onRemoveFilterByComponentType, onRemoveFilterBySPFxVersion,clearAllFilters, onClearTextboxChange,showOnlyScenarios }: React.PropsWithChildren<ISearchBarProps>) => {
```

2024-07-01 19:54 UTC, DevPio reviewed
all set, thanks for the suggestions!

2024-07-07 21:06 UTC, Adam-it approved these changes
@DevPio Awesome work 👏👏
I only found some small styling issues and eslint warnings I resolved myself.
You Rock 🤩

2024-07-07 21:10 UTC, merged