Sample gallery with extension type, Closes #219
pnp/vscode-viva pull request #260
Opened 2024-06-18 19:09 UTC by nicodecleyre

## 🎯 Aim

Adding an extra filter to Sample gallery so that we can filter on the extension type. Filter can only be visible when extension type is selected 'Component Type'

## 📷 Result

![image](https://github.com/pnp/vscode-viva/assets/35696168/c8c2e084-5831-4fc4-861e-ad4c4c0845d7)

## ✅ What was done

- [X] Added Extension filter dropdown
- [X] Added functionality so that extension filter is only visible when extension is selected in the Component Type dropdown
- [X] Added filter functionality so that samples get filtered based on selected value in extension dropdown
- [X] Added filter functionality so that samples don't get filtered when extensions dropdown has selected values  but extension is not selected in component type dropdown

## 🔗 Related issue

Closes: #219

2024-06-18 22:08 UTC, Adam-it commented
Awesome 👏👏👏👏 I will review it ASAP 🤩
You Rock 😍

2024-06-29 22:49 UTC, Adam-it requested changes
@nicodecleyre awesome work so far 👏 
The implementation is really good and clean and I have only some small details I commented. 
The biggest problem I noticed is a small bug that:
I managed to have the extension type filter present not only with extension component type but with webpart as well. Then I selected form customizer type and when I unselected and selected extension component type again it seemed that the form customizer extension type was already selected (the samples were filtered) but it wasn't selected in the picker. Please check the below recording for more details.
https://github.com/pnp/vscode-viva/assets/58668583/0866d980-6d59-4653-8183-745c901cb0eb

2024-06-29 22:49 UTC, Adam-it commented on src/vscode.d.ts
on `dev` branch we don't have this anymore. It was an workaround to introduce the spfx GH chat participant in a really early release with a bit of a hack. We don't need this anymore as it is now shipped together with VS Code. Lets be sure to align before we merge

2024-06-29 22:49 UTC, Adam-it commented on src/webview/view/components/gallery/SearchBar.tsx
> +  // eslint-disable-next-line no-unused-vars
this eslint rule was a total pain so I decided to remove it so that we don't need to add those // disable comments. Lets align and remove this line as well

2024-06-29 22:49 UTC, Adam-it commented on src/webview/view/hooks/useSamples.tsx
> +// eslint-disable-next-line no-unused-vars
same here. We may avoid this now

2024-06-29 22:49 UTC, Adam-it commented on src/constants/Prompts.ts
lets not change this file

2024-06-29 22:49 UTC, Adam-it commented on src/webview/view/components/gallery/SearchBar.tsx
> +        )}
this is a bit tricky. I think we should:
1. move the extensionTypes filter to be next to component type
2. dynamically change the number of columns to 5 so that all of the filters will be in one line (row) and we wont have the scenario checkbox in next row 
![image](https://github.com/pnp/vscode-viva/assets/58668583/0a9ba148-663f-4454-bd45-db57c99bd3fe)

2024-08-05 21:32 UTC, Adam-it requested changes
@nicodecleyre the implementation looks ok but when testing it locally it seems like it is a bit inconsistent with the rest of filters and some behavior is still buggy

Please check below recording for more context.

https://github.com/user-attachments/assets/aac5ccff-6dc7-4db0-960c-92287e315193

- it seems the selected extension type filter are not pointed out in the text box and the checkbox are not marked
- the picked option are not shown in the tag below as other filters
- when we 'clear all' the extension gets unselected but the extension type select gets not hidden

2024-08-10 16:55 UTC, nicodecleyre commented
> @nicodecleyre the implementation looks ok but when testing it locally it seems like it is a bit inconsistent with the rest of filters and some behavior is still buggy
> 
> Please check below recording for more context.
> 
>  PR.test.mp4 
> * it seems the selected extension type filter are not pointed out in the text box and the checkbox are not marked
> * the picked option are not shown in the tag below as other filters
> * when we 'clear all' the extension gets unselected but the extension type select gets not hidden

Thx @Adam-it, indeed a bit inconsistent like you said. Did a couple of changes and tested. Seems to work fine on my end.

Let me know if you find other bugs 🙏

2024-08-25 23:03 UTC, Adam-it approved these changes
Looks and works really good 👍
Added some minor styling tweaks. 
Awesome work 👏 You Rock 🤩

2024-08-25 23:04 UTC, merged