feat: :sparkles: add guidance for component and extension types in sc…
pnp/vscode-viva pull request #273
Opened 2024-07-11 15:54 UTC by DevPio

…affolding form

## 🎯 Aim
 add guidance for component and extension types in scaffolding

## 📷 Result

![Gravando 2024-07-11 123539](https://github.com/pnp/vscode-viva/assets/64063580/14ef4c47-59c0-4949-854d-63741f074ae3)

## ✅ What was done

- [] not done
- [X] done

## 🔗 Related issue

Closes: #268

2024-07-12 21:19 UTC, Adam-it requested changes
@DevPio awesome work 👏👏👏
I have some small comments and one topic I would like to recheck before we proceed 👍

2024-07-12 21:19 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/LabelWithTooltip.tsx
lets move this file to `components/controls` as it seems something that may be reused between all webviews we use in this extension and no something which is spfxProject specific

2024-07-12 21:19 UTC, Adam-it commented on src/constants/ComponentTypesDetails.ts
> +export const ComponentTypesDetails: ComponentTypeDetailsType = {
what if instead of introducing new object we could just add those descriptions to existing places. 
For example we could add the descriptions to `ComponentTypes` as a new property there `description`. This way we will have it a bit cleaner and have less places to handle. 
What is your take on that?

2024-07-15 15:49 UTC, DevPio commented on src/constants/ComponentTypesDetails.ts
> +export const ComponentTypesDetails: ComponentTypeDetailsType = {
I will follow the idea; I also believe the code will be cleaner. I did it this way for simplicity. Thank you for the guidance.

2024-07-15 21:47 UTC, Adam-it commented on src/constants/ComponentTypesDetails.ts
> +export const ComponentTypesDetails: ComponentTypeDetailsType = {
awesome 👍 As soon as you think you are ready for another round please do mark the PR as 'Ready for review'.

2024-08-05 21:11 UTC, Adam-it requested changes
Tested it locally and works perfectly ✅
Lets work on the content a bit and we are good to go 🚀

2024-08-05 21:11 UTC, Adam-it commented on src/webview/view/components/forms/spfxProject/GeneralInfoStep.tsx
> +                    <LabelWithTooltip label={"Component Type"} tooltip={getComponentType ? getComponentType.description : ""} />
lets keep the question label for that. What do you think?

```suggestion
                    <LabelWithTooltip label={"What component you wish to create?"} tooltip={getComponentType ? getComponentType.description : ""} />
```

2024-09-08 01:37 UTC, Adam-it commented
@DevPio  we just had a new major v4 release. Due to this the `dev` branch was rebased to align with `main` branch. 
Please rebase your local branch to update this PR before we may move forward. 
Please let me know if you need any kind of help with that

2024-09-17 08:30 UTC, Adam-it commented
@DevPio any updates on this PR? 
Please let me know if you need some help 👍

2024-09-27 20:54 UTC, Adam-it approved these changes

2024-09-27 20:55 UTC, Adam-it commented
Awesome work 👏
Added some minor tweaks to the changes 👍
You Rock 🤩

2024-09-27 20:55 UTC, merged