Present solutions deployed per app catalog. Closes #215
pnp/vscode-viva pull request #319
Opened 2024-10-06 19:54 UTC by Saurabh7019

## 🎯 Aim

> Present solutions deployed per app catalog and add additional app-related actions (deploy, retract, remove, enable, disable etc.)

## 📷 Result

![image](https://github.com/user-attachments/assets/9bf83f77-83ea-44a6-9fe5-fec24e47ac12)

## ✅ What was done

- [X] Dynamic loading of children for ActionTreeItem
- [X] Present solutions deployed per app catalog
- [X] Allow to disable and enable a solution
- [X] Allow to deploy and retract a solution
- [X] Allow to remove a solution
- [X] Clicking on app link should go to the solution appStore.aspx page
- [] Allow to move solutions between app catalogs (from site level to tenant level and the other way around)
- [] Allow to add a webpart to all sites

## 🔗 Related issue

> Closes #215

2024-10-07 23:54 UTC, Adam-it requested changes
@Saurabh7019 awesome work so far 👏👏👏 You Rock 🤩
I added few minor comments. Please do give them a recheck 🙏
Also I noticed some things when testing we might want to fixup before we merge:
It seems I was always unable to remove an app 🤔
![image](https://github.com/user-attachments/assets/17917d6d-61d1-4c8e-ba87-58179a8bce9c)

also it seems that now it is impossible to redirect to a tenant app catalog or site-level app catalog when clicking on the link. This is due to the fact that those are now groups not single items. But still I think it was pretty nice to go to the app catalog by clicking on the item. What if we add this as a additional action next to the group? when clicking on it we could still open the appcatalog to get easy transfer to it. What do you think?

This PR is really awesome and I already see a lot of potential it opens up to more amazing functionalities this area may bring 🤩

2024-10-07 23:54 UTC, Adam-it commented on src/panels/CommandPanel.ts
> +            const appStoreUrl = `${tenantAppCatalogUrl}/_layouts/15/appStore.aspx`;
currently when clicking on any app we will be redirected to the general appStore link. The idea was to be redirected to the `/appDetail/` page  to see details of that app from the store 
![image](https://github.com/user-attachments/assets/f8b6efd4-be91-450a-ab84-4aad75ac0929)

2024-10-07 23:54 UTC, Adam-it commented on src/services/actions/CliActions.ts
> +interface AppCatalogApp {
lets move this to `model` folder

2024-10-08 14:28 UTC, Saurabh7019 commented
> But still I think it was pretty nice to go to the app catalog by clicking on the item

Oh, I missed that! I'll include it today. Should I just make the node itself a link, or would you prefer an action for it? The App Catalog node already looks like a link, so as a user I would think it should be clickable. Users can click on the node to navigate directly to the App Catalog, and click the arrow on the left to expand and see the list of apps.

![image](https://github.com/user-attachments/assets/4b2fa372-fd09-4941-b798-41b7b03d4178)

or, I can provide additional action, if you prefer that?

2024-10-08 20:27 UTC, Adam-it commented
@Saurabh7019 I'll leave it up to you. For me any of the options you mentioned are fine 👍 as long as we keep this functionality as I think it is just helpful. 
I will leave the decision up to you 👍 this is an open-source and community-driven tool and I am confident you will pick the best option

2024-10-08 23:18 UTC, Adam-it commented
@Saurabh7019 I also not just realized we should update the guidance in the readme and screenshots that present this part of toolkit to keep this up to date 👍

2024-10-14 23:29 UTC, merged

2024-10-14 23:31 UTC, Adam-it commented
Awesome work 👏👏👏. You Rock 🤩