First commit
pnp/vscode-viva pull request #323
Opened 2024-10-13 18:44 UTC by nicodecleyre

## 🎯 Aim

Adding the tour options and both md & tour options as settings for the upgrade and validate actions

## 📷 Result

![image](https://github.com/user-attachments/assets/582ac622-aa94-43f5-a3ae-644d24d36f17)

## ✅ What was done

- [X] Added `Md`, `Tour`, `Both` as upgrade options in the settings 
- [X] Added `Md`, `Tour`, `Both` as validate options in the settings 
- [X] Added tour logic to code for the upgrade option
- [X] Added tour logic to code for the validate option

## 🔗 Related issue

Closes: #188

2024-10-13 19:02 UTC, Adam-it commented
Awesome. Thank you for another awesome contribution. I will review it ASAP

2024-10-14 23:46 UTC, Adam-it requested changes
@nicodecleyre Awesome work so far 👏👏👏👏
I tested it and works really good. During my tests and review I noticed some small details we could sort out before we merge 👍
Please do give them a double check 🙏

2024-10-14 23:46 UTC, Adam-it commented on src/services/actions/CliActions.ts
> +          commands.executeCommand('codetour.startTour');
the problem with this approach is that it will run code tour even if nothing was found. in this case we see a picker to run tour but there is non to run. this may be very confusing and I suggest we should run the code tour command only when something was created, so the CLI command did return something
![image](https://github.com/user-attachments/assets/68efcacc-e40d-4bee-8db4-4c230ed06503)

The same applies to the Upgrade report

2024-10-14 23:48 UTC, Adam-it commented
@nicodecleyre I also did some merging to the dev branch. May I kindly ask you to rebase against latest dev

2024-10-19 21:00 UTC, Adam-it commented
@nicodecleyre we just rebased `dev` branch with latest `main`. 
May I kindly ask you to align your branch 🙏 Cheers

2024-10-21 19:04 UTC, nicodecleyre commented on src/services/actions/CliActions.ts
> +import * as fs from 'fs';
In the original commit no, but now we do as we have to check if the file exists

2024-10-22 09:34 UTC, nicodecleyre commented on src/services/actions/CliActions.ts
> +          commands.executeCommand('codetour.startTour');
`spfx project upgrade` & `spfx project doctor` don't return anything if the option is `tour`, so we have to check if the file exists

2024-10-22 09:35 UTC, nicodecleyre commented
> @nicodecleyre we just rebased `dev` branch with latest `main`. May I kindly ask you to align your branch 🙏 Cheers

Still working on it, having a little trouble with the rebase 😆

2024-10-30 07:20 UTC, Adam-it requested changes
@nicodecleyre I think we are in a much better state now. I played with it a lot and I think it is a nice feature. I noticed some two small improvements we could double check before we proceed but those are not that important I guess.

What is my main concern, and this is more a question if you experienced the same behavior, is:
when I had `both` for validation and upgrade I noticed that sometimes when clicked on the upgrade action even though the tour was generated and the json was present te codeTour extension did not start it but instead it asked which tour should it run and none was available? I was wondering if the tour extension triggered just before the tour json was present 🤔 Maybe  we could add a bit of wait as I checked this is already awaited so I am not sure  why this behavior and I would need a bit deeper dive on this myself
![image](https://github.com/user-attachments/assets/861069d9-3a5d-4398-af3a-639590b758fd)

And then the strange part. When I had the validation tour created first and then I clicked on the upgrade action the extension kicked of the validation tour 😮 instead of asking which tour should be triggered?
![image](https://github.com/user-attachments/assets/1818deab-946d-400f-961e-769466bc9dfd)

I was wondering did you maybe researched if there was a way to pass down to codeTour which specific tour should start, so we could avoid the picker when we have both the validation and upgrade tours? I will try to research this myself as well.

Other than the above concerns/questions I think we are all good and getting closer to get this merged 👍👍I wanted to make this feature perfect before we proceed 🤩. I will try to recheck some of the stuff mentioned above myself next week

2024-10-30 07:20 UTC, Adam-it commented on src/services/actions/CliActions.ts
> +          await CliExecuter.execute('spfx project upgrade', 'tour');
I was wondering if we could just have `if` blocks in which we check for either the specific type/method, like `markdown` or `tour`  and check for `both`. In this case we don't need to check explicitly for `both` and we will avoid code repetition. What do you think? I guess it should work

```suggestion
        if (projectUpgradeOutputMode === 'markdown' || projectUpgradeOutputMode === 'both') {
          resultMd = await CliExecuter.execute('spfx project upgrade', 'md');
          CliActions.handleMarkdownResult(resultMd, wsFolder, 'upgrade');
        } 
        
        if (projectUpgradeOutputMode === 'code tour' || projectUpgradeOutputMode === 'both') {
          await CliExecuter.execute('spfx project upgrade', 'tour');
          CliActions.handleTourResult(wsFolder, 'upgrade');
        }```

2024-10-30 07:20 UTC, Adam-it commented on src/services/actions/CliActions.ts
> +      Notifications.error('Validation tour file not found. Cannot start Code Tour.');
the error may be misleading as it may not always be the validation tour but also it may be the upgrade tour

2024-11-15 12:04 UTC, nicodecleyre commented
Hi Adam, you're right, there seems to be a sort of hickup. It seems that the setup right now "still lives in the past". I did some testing and this are the results:
- run validate: no code tour selectable
- run validate: validate code tour selectable
- run upgrade: validate code tour selectable
- run validate: validate & upgrade code tour selectable.

So it seems that only the tour from the previous run is selectable. Timeout doesn't seem to solve the problem right away. Will have to dig deeper.

2024-11-15 23:09 UTC, Adam-it commented
> Hi Adam, you're right, there seems to be a sort of hickup. It seems that the setup right now "still lives in the past". I did some testing and this are the results:
> 
> * run validate: no code tour selectable
> * run validate: validate code tour selectable
> * run upgrade: validate code tour selectable
> * run validate: validate & upgrade code tour selectable.
> 
> So it seems that only the tour from the previous run is selectable. Timeout doesn't seem to solve the problem right away. Will have to dig deeper.

I wonder if we could open a issue in the code tour extension repo to ask for some advice 🤔?

2024-11-20 13:31 UTC, nicodecleyre commented
> > Hi Adam, you're right, there seems to be a sort of hickup. It seems that the setup right now "still lives in the past". I did some testing and this are the results:
> > 
> > * run validate: no code tour selectable
> > * run validate: validate code tour selectable
> > * run upgrade: validate code tour selectable
> > * run validate: validate & upgrade code tour selectable.
> > 
> > So it seems that only the tour from the previous run is selectable. Timeout doesn't seem to solve the problem right away. Will have to dig deeper.
> 
> I wonder if we could open a issue in the code tour extension repo to ask for some advice 🤔?

It's not a tour related issue it seems. I've tested with 100, 200 & 300 ms which didn't do the trick. But with 500 ms latency, it seems to work (tested aaaaaaa lot 😜 ) and 500 is still acceptable for end users i guess. Will update the PR

2024-11-23 22:16 UTC, Adam-it approved these changes
Awesome work 👏👏👏👏
I added a minor fixup in the code flow
Tested it locally and works really good 👍 You Rock 🤩

2024-11-23 22:18 UTC, merged